#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.7
# from Racc grammer file "".
#

require 'racc/parser.rb'

class Yay
class ParserGen < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 54)

...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    -7,   -25,    33,    17,    25,    17,   -25,    12,    22,    22,
    33,    20,    30,     9,    10,    12,     2,     4,     8,     9,
    10,    12,    28,    36,    31,    29,    29,    19,    -2,    17,
    38,    29,    38 ]

racc_action_check = [
     7,     6,    21,    17,    10,     9,     6,    21,     6,     7,
    23,     4,    19,    23,    23,    23,     0,     0,     0,     0,
     0,     0,    18,    24,    20,    18,    24,     3,     2,     1,
    27,    29,    35 ]

racc_action_pointer = [
    14,    18,    28,    27,     9,   nil,    -1,     0,   nil,    -6,
     2,   nil,   nil,   nil,   nil,   nil,   nil,    -8,    17,    12,
    22,     0,   nil,     8,    18,   nil,   nil,    20,   nil,    23,
   nil,   nil,   nil,   nil,   nil,    22,   nil,   nil,   nil,   nil,
   nil ]

racc_action_default = [
    -5,   -29,   -20,   -30,   -30,    -1,   -19,   -25,    -4,   -29,
   -30,    -8,   -21,    -9,   -10,   -11,   -12,   -29,   -30,   -30,
   -30,   -30,   -24,   -30,   -30,   -17,   -28,   -27,   -14,   -23,
    41,    -3,   -18,   -20,    -6,   -27,   -16,   -13,   -26,   -22,
   -15 ]

racc_goto_table = [
     5,    18,    27,    37,    21,    23,    32,     3,    35,    24,
   nil,    40,   nil,    39,   nil,   nil,   nil,    26,   nil,   nil,
   nil,   nil,   nil,    34 ]

racc_goto_check = [
     2,    11,    12,    13,     4,     4,    10,     1,    12,    11,
   nil,    13,   nil,    12,   nil,   nil,   nil,    11,   nil,   nil,
   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     7,     0,   nil,    -2,   nil,   nil,   nil,   nil,   nil,
   -15,     0,   -16,   -24,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     7,   nil,    11,    13,    14,    15,    16,
     1,   nil,   nil,   nil,     6 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 13, :_reduce_1,
  1, 13, :_reduce_2,
  3, 13, :_reduce_3,
  1, 13, :_reduce_4,
  0, 13, :_reduce_5,
  3, 14, :_reduce_6,
  1, 14, :_reduce_7,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  4, 17, :_reduce_13,
  3, 18, :_reduce_14,
  4, 19, :_reduce_15,
  3, 20, :_reduce_16,
  2, 21, :_reduce_17,
  3, 22, :_reduce_18,
  1, 22, :_reduce_19,
  1, 26, :_reduce_20,
  1, 26, :_reduce_21,
  2, 24, :_reduce_22,
  1, 24, :_reduce_23,
  1, 16, :_reduce_24,
  0, 16, :_reduce_25,
  1, 25, :_reduce_26,
  0, 25, :_reduce_27,
  2, 23, :_reduce_28,
  0, 23, :_reduce_29 ]

racc_reduce_n = 30

racc_shift_n = 41

racc_token_table = {
  false => 0,
  :error => 1,
  :literal => 2,
  :install => 3,
  :list_installed => 4,
  :variable => 5,
  :include => 6,
  :regex => 7,
  :colour => 8,
  :and => 9,
  :line => 10,
  :verb => 11 }

racc_nt_base = 12

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "literal",
  "install",
  "list_installed",
  "variable",
  "include",
  "regex",
  "colour",
  "and",
  "line",
  "verb",
  "$start",
  "body",
  "command_list",
  "command",
  "and_opt",
  "match",
  "assignment",
  "substitution",
  "equivalence",
  "include_file",
  "string_list",
  "verbs_opt",
  "colour_list",
  "line_opt",
  "string" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 5)
  def _reduce_1(val, _values, result)
      
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 6)
  def _reduce_2(val, _values, result)
     include_file val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 7)
  def _reduce_3(val, _values, result)
     install_file val[1], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 8)
  def _reduce_4(val, _values, result)
     list_installed 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 9)
  def _reduce_5(val, _values, result)
     use_default_file 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 11)
  def _reduce_6(val, _values, result)
      
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 12)
  def _reduce_7(val, _values, result)
      
    result
  end
.,.,

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

module_eval(<<'.,.,', 'grammar.y', 20)
  def _reduce_13(val, _values, result)
     @ruleset.add_match val[0], handle_colours(val[2]), val[3] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 22)
  def _reduce_14(val, _values, result)
     @ruleset.add_assignment val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 24)
  def _reduce_15(val, _values, result)
     @ruleset.add_substitution val[0], handle_colours(val[2]), val[3] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 26)
  def _reduce_16(val, _values, result)
     @ruleset.add_equivalence val[0], val[2]  
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 28)
  def _reduce_17(val, _values, result)
     include_file val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 30)
  def _reduce_18(val, _values, result)
     val[2].unshift(val[0]); result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 31)
  def _reduce_19(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 33)
  def _reduce_20(val, _values, result)
     result = handle_string(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 34)
  def _reduce_21(val, _values, result)
     result = handle_regex(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 36)
  def _reduce_22(val, _values, result)
     val[1].unshift(val[0].to_sym); result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 37)
  def _reduce_23(val, _values, result)
     result = [val[0].to_sym] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 39)
  def _reduce_24(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 40)
  def _reduce_25(val, _values, result)
     
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 42)
  def _reduce_26(val, _values, result)
     result = true 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 43)
  def _reduce_27(val, _values, result)
     result = false 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 45)
  def _reduce_28(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 46)
  def _reduce_29(val, _values, result)
     
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ParserGen

end # class Yay
